### ISSUE TITLE
01 - Hello world json response

### ISSUE THREAD

**Issue by davsclaus** [mmistretta/RHSummit2018Camel3ScaleLab#3]
The Camel route is configured to return json payload. But the hello world message is just a text.
Its not valid json.

The response should be something alike
```
{ "reply": "Hello World" }
```
However there is an issue in that Camel where it will auto quote the response as well when using simple.
```
$ curl -i http://localhost:8080/camel/hello
HTTP/1.1 200
X-Application-Context: application
accept: */*
breadcrumbId: ID-ovpn-117-107-ams2-redhat-com-1525350385233-0-1
user-agent: curl/7.54.0
Content-Type: application/json
Transfer-Encoding: chunked
Date: Thu, 03 May 2018 12:26:29 GMT

"{ \"reply\": \"Hello World, Claus\" }"
```

The response body should just be
```
{ \"reply\": \"Hello World, Claus\" }
```

**Comment by davsclaus** [comment]
We can use a POJO instead then it will map that to JSon which is potentially easier than to fiddle with a string trying to build a json representation.

**Comment by mmistretta** [comment]
I think i fixed this on the complete-camel-route branch, let me know your thoughts

**Comment by davsclaus** [comment]
Yeah a POJO can resolve this. However I actually thought we had this fixed in Apache Camel upstream as well with the quotes. Its because its a string value being converted to json that then get quoted. We can log a JIRA upstream but it wont get fixed in the version we would use for summit, and hence the POJO solution is better.
