### ISSUE TITLE
Make mvn spring-boot:run without fabric8 plugin activated

### ISSUE THREAD

**Issue by davsclaus** [mmistretta/RHSummit2018Camel3ScaleLab#7]
Hi

I think we should have a standalone step where people build the sample project without OS or fabric8 maven plugin. And run it locally with mvn spring-boot run.

Then when you go to deploy to openshift it talks about adding the fabric8-maven-plugin. And potentially configure the shell to use OS cluster (minishift docker-env) and for OS online you need to setup some ENV vars to point to that, or login via the oc client tool.

**Comment by mmistretta** [comment]
do you mean something different than the end of  this?
https://github.com/mmistretta/RHSummit2018Camel3ScaleLab/tree/master/01-create-camel-route

**Comment by mmistretta** [comment]
editted the steps and adjusted master to not have the plugin
