### ISSUE TITLE
Update the readmes of the 1, 2, 3

### ISSUE THREAD

**Issue by davsclaus** [mmistretta/RHSummit2018Camel3ScaleLab#8]
The complete camel route has been polished and updated to be a bit more leaner. We should go over the readme files in the 01, 02, 03 folders and update them accordingly.

Also I think the f-m-p plugin should only be added when you have the "deploy to OS" step. All before that should be standalone - that is easier for people. eg get it running locallly, and then only thereafter "battle" with openshift/cloud world.

**Comment by mmistretta** [comment]
Will do that today.

**Comment by mmistretta** [comment]
updated!
