### ISSUE TITLE
Move step about fabric8 deployment configure file to OS step

### ISSUE THREAD

**Issue by davsclaus** [mmistretta/RHSummit2018Camel3ScaleLab#9]
I think at
https://github.com/mmistretta/RHSummit2018Camel3ScaleLab/tree/master/01-create-camel-route

The step about the fabric8 file: src/main/faric8/deployment.yml
Should be moved to the lab where you deploy to OS, eg 02.

Also I assume we add this to not let the pod take up too much resources on OS online.

**Comment by davsclaus** [comment]
Ah okay they shouldnt create this file manually. We can maybe update the readme in 01 that this file is something we cover more in 02

**Comment by mmistretta** [comment]
I'm confused. They dont create the file at all. It just is in the project.  I just ran through the whole lab on my husband's machien which started with nothing and all was well.  We can adjust that, but I likely won't have time until tomorrow to look at this stuff again.

**Comment by davsclaus** [comment]
Yeah sorry it was my mistake.

I was probably trying to look at this workshop as where you can create a vanilla standard Camel/Fuse project as standalone Java, and then only later add the bits for OS deployment via the fabric8 maven plugin.
